# Use root/example as user/password credentials
version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ollama-network

  python-app:
    build: .
    ports:
      - "8000:8000"  # adjust to match your Python app's port
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - ollama-network

volumes:
  ollama-data:

networks:
  ollama-network:
    driver: bridge